import { complete, truncate } from "../agent/client";
import { formatMoney, type LedgerEntry, type Money } from "../contracts";

/**
 * The vendor email drafter.
 *
 * This exists because of an honest limitation. Pausing a mandate stops the
 * money; it does not cancel the subscription. The vendor still believes there
 * is a contract, and somebody has to tell them. Pretending otherwise would be
 * the kind of gap that a judge finds in thirty seconds.
 *
 * So the system drafts the email and attaches it to the ledger entry. It never
 * sends it. Sending would be an outbound action taken on a vendor relationship
 * without a human reading the words first, which is exactly the class of thing
 * this product exists to prevent — the fact that an email is not money does
 * not make it something an agent should do unattended.
 *
 * The draft is generated by the model when one is configured and by a template
 * otherwise, and either way it is a draft.
 */

export type EmailKind = "CANCEL" | "PAUSE" | "SEAT_REDUCTION" | "DISPUTE";

export interface EmailDraft {
  kind: EmailKind;
  subject: string;
  body: string;
  /** Always false. There is no send path in this module. */
  sent: false;
  /** What produced the wording — a model id, or "template". */
  draftedBy: string;
}

interface DraftInput {
  kind: EmailKind;
  vendorName: string;
  amount: Money | null;
  seatsBefore?: number;
  seatsAfter?: number;
  /** The policy sentence that led here, quoted to the vendor if useful. */
  reason: string;
}

/**
 * The template. Used when no model is configured, and used as the fallback
 * when the model is unreachable — a drafter that fails to draft would leave
 * the "pausing is not cancelling" gap open again.
 */
export function templateDraft(input: DraftInput): EmailDraft {
  const { vendorName, amount } = input;
  const money = amount ? formatMoney(amount) : null;

  switch (input.kind) {
    case "CANCEL":
      return {
        kind: "CANCEL",
        subject: `Cancellation of our ${vendorName} subscription`,
        body: [
          `Hello,`,
          ``,
          `We are cancelling our ${vendorName} subscription effective at the end of the current billing period. Please confirm the cancellation and the final billing date.`,
          ``,
          `We have also stopped the payment authorization on our side, so no further charges will be authorized regardless of billing state.`,
          ``,
          `Thank you,`,
          `Finance`,
        ].join("\n"),
        sent: false,
        draftedBy: "template",
      };

    case "PAUSE":
      return {
        kind: "PAUSE",
        subject: `Pausing billing on our ${vendorName} subscription`,
        body: [
          `Hello,`,
          ``,
          `We have paused the payment authorization for our ${vendorName} subscription${money ? ` (${money} per cycle)` : ""} while we review usage.`,
          ``,
          `To be clear about what that means on your side: the subscription itself has not been cancelled, but charges against it will be declined until we resume. We wanted to tell you directly rather than have a payment fail without explanation.`,
          ``,
          `We will confirm within the next billing cycle whether we are resuming or cancelling.`,
          ``,
          `Thank you,`,
          `Finance`,
        ].join("\n"),
        sent: false,
        draftedBy: "template",
      };

    case "SEAT_REDUCTION":
      return {
        kind: "SEAT_REDUCTION",
        subject: `Reducing our ${vendorName} seat count`,
        body: [
          `Hello,`,
          ``,
          `We would like to reduce our ${vendorName} plan from ${input.seatsBefore ?? "our current"} seats to ${input.seatsAfter ?? "fewer"} seats at the next renewal. The additional seats have shown no activity over the last billing period.`,
          ``,
          `Please confirm the adjusted amount before the renewal date.`,
          ``,
          `Thank you,`,
          `Finance`,
        ].join("\n"),
        sent: false,
        draftedBy: "template",
      };

    case "DISPUTE":
      return {
        kind: "DISPUTE",
        subject: `Question about the upcoming ${vendorName} charge`,
        body: [
          `Hello,`,
          ``,
          `We have a question about the upcoming ${vendorName} renewal${money ? ` of ${money}` : ""}. ${input.reason}`,
          ``,
          `We have held the payment pending your reply. Could you confirm the amount and what changed?`,
          ``,
          `Thank you,`,
          `Finance`,
        ].join("\n"),
        sent: false,
        draftedBy: "template",
      };
  }
}

const SYSTEM_PROMPT = `You draft short, plain business emails from a finance team to a software vendor.

Rules:
  - Four to eight sentences. No pleasantries beyond a greeting and a sign-off.
  - State the facts you are given. Do not invent contract terms, dates,
    account numbers, or prior conversations.
  - Never claim a decision has been approved, escalated, or finalized beyond
    what you are told.
  - When billing has been paused rather than cancelled, say so plainly. Do not
    let the vendor infer a cancellation that did not happen.
  - Sign off as "Finance".

Respond with a single JSON object: {"subject": "...", "body": "..."}`;

const RESPONSE_SCHEMA = {
  type: "object",
  properties: {
    subject: { type: "string" },
    body: { type: "string" },
  },
  required: ["subject", "body"],
  additionalProperties: false,
} as const;

/**
 * Draft an email. Never sends one.
 *
 * Falls back to the template on any model failure, because the point of this
 * component is that the vendor gets told — a missing draft would reopen the
 * gap this exists to close.
 */
export async function draftEmail(input: DraftInput): Promise<EmailDraft> {
  const fallback = templateDraft(input);

  if (process.env.AGENT_MODE !== "live" || !process.env.ANTHROPIC_API_KEY) {
    return fallback;
  }

  const facts = [
    `Vendor: ${input.vendorName}`,
    `Situation: ${input.kind}`,
    input.amount ? `Amount per cycle: ${formatMoney(input.amount)}` : null,
    input.seatsBefore !== undefined
      ? `Seats currently licensed: ${input.seatsBefore}`
      : null,
    input.seatsAfter !== undefined
      ? `Seats we want: ${input.seatsAfter}`
      : null,
    `Why: ${input.reason}`,
  ]
    .filter(Boolean)
    .join("\n");

  const result = await complete({
    system: SYSTEM_PROMPT,
    prompt: facts,
    maxTokens: 800,
    schema: RESPONSE_SCHEMA as unknown as Record<string, unknown>,
  });

  if (!result.ok) return fallback;

  try {
    const parsed = JSON.parse(result.text) as Record<string, unknown>;
    if (
      typeof parsed.subject !== "string" ||
      typeof parsed.body !== "string" ||
      !parsed.subject.trim() ||
      !parsed.body.trim()
    ) {
      return fallback;
    }
    return {
      kind: input.kind,
      subject: truncate(parsed.subject, 200),
      body: truncate(parsed.body, 2000),
      sent: false,
      draftedBy: result.model,
    };
  } catch {
    return fallback;
  }
}

/** Whether an outcome warrants telling the vendor something. */
export function needsVendorEmail(entry: LedgerEntry): EmailKind | null {
  if (entry.outcome === "NETWORK_DECLINE") return "PAUSE";
  if (entry.decision === "DENY") return "CANCEL";
  if (entry.reason === "AMOUNT_EXCEEDS_CEILING") return "DISPUTE";
  return null;
}
