/**
 * ASK A MODEL FOR NEW ATTACKS, AND FREEZE THE ONES THAT SURVIVE.
 *
 *   npm run attacks:generate [count]
 *
 * Writes `lib/adversary/generated.ts` and bumps the corpus version. Nothing runs
 * the new attacks: that is the gauntlet's job, and it happens on a frozen
 * corpus with a digest every record cites.
 *
 * ---------------------------------------------------------------------------
 * REVIEW THE DIFF BEFORE COMMITTING IT.
 *
 * The validator rebuilds every entry from scratch and refuses anything that
 * could let a model grade its own homework — but it cannot tell you whether an
 * attack is INTERESTING. That judgement is yours, and it is why this writes
 * source you can read rather than rows in a table you cannot.
 * ---------------------------------------------------------------------------
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { CORPUS, corpusDigest } from "../lib/adversary/corpus";
import { CORPUS_VERSION, GENERATED_ENTRIES } from "../lib/adversary/generated";
import { generateAttacks } from "../lib/adversary/generate";
import type { AttackEntry } from "../lib/adversary/corpus";

const TARGET = resolve(process.cwd(), "lib/adversary/generated.ts");

/** corpus-1 → corpus-2. */
function bump(version: string): string {
  const match = /^corpus-(\d+)$/.exec(version);
  return match ? `corpus-${Number(match[1]) + 1}` : "corpus-2";
}

function render(version: string, entries: readonly AttackEntry[]): string {
  const body =
    entries.length === 0
      ? "[]"
      : JSON.stringify(entries, null, 2)
          .split("\n")
          .map((line, i) => (i === 0 ? line : `  ${line}`))
          .join("\n");

  return `import type { AttackEntry } from "./corpus";

/**
 * GENERATED ATTACKS, FROZEN.
 *
 * ---------------------------------------------------------------------------
 * THIS FILE IS WRITTEN BY A SCRIPT AND REVIEWED BY A HUMAN.
 *
 *   npm run attacks:generate
 *
 * A model proposes attacks; \`lib/adversary/generate.ts\` validates and rebuilds
 * each one from scratch; the script writes the survivors here and bumps
 * \`CORPUS_VERSION\`. Only then can the gauntlet run them.
 *
 * Committing them as source rather than storing them in a database is the
 * point. A generated corpus in git is diffable, reviewable, and travels with
 * the repository — so "the attacker got smarter last night" is a pull request
 * somebody can read, not an opaque row somewhere.
 *
 * ---------------------------------------------------------------------------
 * WHY FREEZING IS WHAT MAKES A NONDETERMINISTIC GENERATOR USABLE
 *
 * A model that invents attacks at run time would make every gauntlet run
 * incomparable to the last, and a signed record citing "corpus-2" would mean
 * nothing. Generating, freezing, and only then running keeps the harness
 * reproducible while the corpus grows.
 * ---------------------------------------------------------------------------
 */

/**
 * Bumped by the generator every time it freezes new attacks.
 *
 * Records cite this AND the corpus digest, so a version that was quietly edited
 * afterwards stops matching every record that claimed it.
 */
export const CORPUS_VERSION = ${JSON.stringify(version)};

export const GENERATED_ENTRIES: readonly AttackEntry[] = Object.freeze(${body} as AttackEntry[]);
`;
}

async function main() {
  const count = Number(process.argv[2] ?? 5);
  if (!Number.isInteger(count) || count < 1 || count > 20) {
    console.error("count must be an integer between 1 and 20");
    process.exitCode = 2;
    return;
  }

  console.log(`corpus ${CORPUS_VERSION}: ${CORPUS.length} attacks, digest ${corpusDigest().slice(0, 16)}…`);
  console.log(`asking for ${count} novel attacks…\n`);

  const outcome = await generateAttacks({ existing: CORPUS, count });

  if (!outcome.ok) {
    console.error(`generation failed: ${outcome.message}`);
    process.exitCode = 1;
    return;
  }

  const { entries, rejected, generatedBy } = outcome.result;

  console.log(`generated by: ${generatedBy}\n`);

  for (const entry of entries) {
    console.log(`  ACCEPTED  ${entry.id}`);
    console.log(`            [${entry.class}] ${entry.title}`);
    console.log(`            expects ${entry.expect.outcome.join("/")} · aimed at: ${entry.targets}`);
  }

  // Rejections are printed, never swallowed. A generator whose output is mostly
  // discarded is a fact worth seeing.
  for (const item of rejected) {
    console.log(`  rejected  ${item.id}: ${item.reason}`);
  }

  if (entries.length === 0) {
    console.log("\nNothing survived validation. Corpus unchanged.");
    return;
  }

  const version = bump(CORPUS_VERSION);
  const merged = [...GENERATED_ENTRIES, ...entries];
  writeFileSync(TARGET, render(version, merged), "utf8");

  console.log(`\n${entries.length} accepted, ${rejected.length} rejected.`);
  console.log(`wrote lib/adversary/generated.ts — corpus is now ${version}`);
  console.log("");
  console.log("Next: review the diff, run `npm run test`, then re-run the gauntlet.");
  console.log("The digest changes, so previous records no longer claim this corpus.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
