import {
  formatMoney,
  type LedgerEntry,
  type Money,
  type VerdictReason,
} from "../contracts";

/**
 * Deterministic explanation templates.
 *
 * Every explanation in the product is rendered from structured data by the
 * functions below. No language model is involved, and that is the point: an
 * explanation generated by a model is a claim about a decision, whereas an
 * explanation rendered from the decision's own fields is the decision,
 * restated. Only the second kind can be trusted to describe what actually
 * happened.
 *
 * The uniform structure is what makes the ledger read as a system rather than
 * as a collection of individually-worded messages. Every entry answers the
 * same three questions in the same order: what happened, why, and what would
 * have had to be different.
 *
 * Model prose — the agent's rationale — is never mixed into these strings. It
 * is carried on the entry separately and rendered in its own labeled region,
 * because a reader must always be able to tell a verified fact from a
 * plausible sentence.
 */

export interface Explanation {
  /** One sentence: what happened. */
  headline: string;
  /** One sentence: why, citing the rule. */
  reason: string;
  /** The user's own words, when a rule was cited. */
  sourceFragment: string | null;
  /** What would have had to differ. Null when nothing would have. */
  counterfactual: string | null;
  /** What this cost or saved. */
  financialImpact: string;
  /** Always present, always the same shape. */
  attribution: {
    decidedBy: string;
    authorizedBy: string;
    executedBy: string;
    recordedBy: string;
  };
}

const REASON_TEMPLATES: Record<VerdictReason, string> = {
  RULE_MATCHED: "A rule in the active policy addressed this directly.",
  TERMINAL_DEFAULT:
    "No rule in the active policy addressed this, so it required approval.",
  DENIAL_PASS: "A rule in the active policy prohibits this outright.",
  AMOUNT_EXCEEDS_CEILING:
    "The amount is above the ceiling the policy permits without approval.",
  MISSING_EVIDENCE:
    "Part of the evidence needed to decide this was not available.",
  MALFORMED_PROPOSAL:
    "The agent did not produce a usable proposal for this renewal.",
  UNKNOWN_ACTION: "The agent proposed an action this system does not recognize.",
};

function headlineFor(entry: LedgerEntry, amount: Money | null): string {
  const money = amount ? formatMoney(amount) : null;

  switch (entry.outcome) {
    case "EXECUTED":
      return money
        ? `Renewed for ${money}.`
        : "Completed without moving money.";
    case "APPROVED_AND_EXECUTED":
      return `Renewed for ${money ?? "an approved amount"} after human approval.`;
    case "REFUSED":
      return money ? `Refused. ${money} was not spent.` : "Refused.";
    case "ESCALATED":
      return money
        ? `Escalated for approval. ${money} is on hold.`
        : "Escalated for approval.";
    case "REJECTED_BY_HUMAN":
      return money
        ? `Rejected by a human. ${money} was not spent.`
        : "Rejected by a human.";
    case "EXPIRED":
      return "The approval expired before it was acted on. Nothing was charged.";
    case "NETWORK_DECLINE":
      return money
        ? `Declined by the payment network. ${money} was not charged.`
        : "Declined by the payment network.";
    case "ADAPTER_FAILURE":
      return "The payment network did not answer. The outcome is unconfirmed.";
    case "HALTED":
      return "The system halted before adjudicating anything.";
    default:
      return "Recorded.";
  }
}

function counterfactualFor(entry: LedgerEntry): string | null {
  const detail = entry.detail as {
    counterfactual?: {
      kind?: string;
      detail?: {
        ceiling?: number;
        actualAmount?: number;
        missingGaps?: string[];
        blockingRuleId?: string;
      };
    } | null;
  };

  const cf = detail.counterfactual;
  if (!cf || !cf.kind) return null;

  switch (cf.kind) {
    case "AMOUNT_BELOW_CEILING": {
      const ceiling = cf.detail?.ceiling;
      const actual = cf.detail?.actualAmount;
      if (typeof ceiling === "number" && typeof actual === "number") {
        return `At ${formatMoney({ cents: ceiling, currency: "USD" })} or below this would have gone through unattended. It was ${formatMoney({ cents: actual, currency: "USD" })}.`;
      }
      return "With an amount ceiling in the policy this could have gone through unattended.";
    }
    case "EVIDENCE_PRESENT": {
      const gaps = cf.detail?.missingGaps ?? [];
      if (gaps.length === 0) return null;
      return `With ${gaps.map(describeGap).join(" and ")}, this would have been decided without a human.`;
    }
    case "RULE_ABSENT":
      return cf.detail?.blockingRuleId
        ? "Without the rule that prohibits this, it would have been evaluated on its amount."
        : "With a rule addressing this case, it would not have needed approval.";
    case "DIFFERENT_ACTION":
      return "With a well-formed proposal this would have been adjudicated on its merits.";
    default:
      return null;
  }
}

function describeGap(gap: string): string {
  switch (gap) {
    case "NO_USAGE_DATA":
      return "seat usage data";
    case "NO_PRIOR_INVOICE":
      return "a prior invoice to compare against";
    case "NO_CONTRACT_TERMS":
      return "the contract terms";
    case "STALE_USAGE_DATA":
      return "current usage data";
    case "UNKNOWN_VENDOR":
      return "a known payment merchant for this vendor";
    default:
      return gap.toLowerCase().replace(/_/g, " ");
  }
}

function financialImpactFor(entry: LedgerEntry, amount: Money | null): string {
  if (!amount) return "No money was involved.";

  switch (entry.outcome) {
    case "EXECUTED":
    case "APPROVED_AND_EXECUTED":
      return `${formatMoney(amount)} was charged.`;
    case "ADAPTER_FAILURE":
      return `${formatMoney(amount)} may or may not have been charged. This entry is open and needs reconciling.`;
    default:
      return `${formatMoney(amount)} was not charged.`;
  }
}

/** Render an entry. Same shape for every entry, always. */
export function explain(entry: LedgerEntry): Explanation {
  const reason = entry.reason
    ? REASON_TEMPLATES[entry.reason]
    : entry.outcome === "HALTED"
      ? String(
          (entry.detail as { message?: string }).message ??
            "The system halted.",
        )
      : "This was recorded without an adjudication.";

  return {
    headline: headlineFor(entry, entry.amount),
    reason,
    sourceFragment: entry.citedSourceFragment || null,
    counterfactual: counterfactualFor(entry),
    financialImpact: financialImpactFor(entry, entry.amount),
    attribution: {
      decidedBy: entry.decidedBy.label,
      authorizedBy: entry.authorizedBy.label,
      executedBy: entry.executedBy.label,
      recordedBy: entry.recordedBy.label,
    },
  };
}

/** One-line summary for dense list views. Same template for every entry. */
export function summarize(entry: LedgerEntry): string {
  return explain(entry).headline;
}
